### ISSUE TITLE
Bayes settings

### ISSUE THREAD

**Issue by schickel007** [JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL#29]
Wiht activated Bayes-settings, I got this error:

spamd-log:
spamd[27478]: config: failed to parse, now a plugin, skipping, in "(no file)": ok_languages af sq am ar hy eu bs bg be ca zh hr cs da nl en eo et fi fr fy ka de el he hi hu is id ga it ja ko r
spamd[27478]: config: failed to parse line, skipping, in "(no file)": bayes_auto_learn_threshold_non -1.0

Is there missing something?

**Comment by JohnDoh** [comment]
you are really asking in the wrong place. this plugin is simply an interface for saving spamassassin settings into a database. I cannot help you with configuring spamassassin. the only reference I could find to an error like this was on http://wiki.apache.org/spamassassin/UsingSQL where it says it is caused by using a custom query which is not written correctly.
