### ISSUE TITLE
PHP memory exhausted

### ISSUE THREAD

**Issue by polski-g** [JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL#37]
Trying to click on Junk > Bayes Settings, I get the following error in syslog:

Allowed memory size of xxxxx bytes exhausted (tried to allocate 64 bytes) in .../program/lib/Roundcube/rcube_plugin_api.php on line 434

They have a TODO item to ensure there isn't recursion (hasn't been touched in 2 years), but that this happens in only this plugin makes me think its something wrong with sauserprefs specifically.

https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_plugin_api.php

**Comment by JohnDoh** [comment]
i can't think of any reason for that and certainly it does not happen for me. i mean clicking on "bayes settings" is just the same as clicking on other sections. do you have any other plugins enabled? if so try with them disabled.

without some more to go on so that I can recreate it I'm not sure there is anything I can do about this generic error.

**Comment by JohnDoh** [comment]
no feedback
