### ISSUE TITLE
Include additional SA options

### ISSUE THREAD

**Issue by nuxwin** [JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL#40]
It could be interessting to provide the administrator a way to register it own sections and preferences.

In order, administrator should be able to:

- Add preferences to any existent section
- Create new section

ATM, the plugin only provide restricted list of SA preferences. For instance, the `use_auto_whitelist` AWL preference is missing.

Thank you.

**Comment by JohnDoh** [comment]
There are hooks so that other plugins can interact with both the list of sections and contents of those sections. Please see the readme for details.

**Comment by nuxwin** [comment]
@JohnDoh 

If I understand well, you're providing a plugin for management of SA preferences which itself requires other 3rd-party plugins for managing more SA preferences... Don't get me wrong but that is a quite strange, isn't it?

**Comment by JohnDoh** [comment]
It does not require any other plugins. sauserprefs works on its own. the plugin hooks provide an exentisble way customise it.

I'm not sure what the alternative would be. Do you think that in the config file it should be possible to somehow define all the various optoins, their field types, their values, how they are displayed on the screen and how the input is validated and saved? That would be a huge and complicated config file. And iimit an admin to only interacting with the options themsevles while the plugin hooks let you control the layout too.

If you would like to see more options added to the plugin I'm happy to consider them but please provide details of those optoins rather than simply saying some are missing. I do not think it is right that all SA config options should be exposed via the plugin as I think some options are not for end users.

**Comment by nuxwin** [comment]
@JohnDoh 

My thinking is that the plugin should support at least all core user preferences, including those from core plugins. And of course, one administrator could just disable them through the `sauserprefs_dont_override` configuration parameter by either naming them explicitely or using sections as it is already possible. But that is only my opinion ;)

About missing user preferences, my thinking was about those:
- use_auto_whitelist
- score USER_IN_BLACKLIST
- score USER_IN_WHITELIST

Thank you for your consideration.
